version: "3"

services:
  api:
    build: ./app
    expose:
      - 8000
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 5
    restart: always
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    command: 
      - "postgres"
      - "-c"
      - "max_connections=400"
      - "-c"
      - "shared_buffers=2GB"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=admin@bde-cs.fr
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./pgadmin/:/var/lib/pgadmin/storage
  nginx:
    build: ./nginx
    ports: 
      - 1337:80
    depends_on:
      - api
    restart: always
    
volumes:
  psql:
    