"""corrected typos

Revision ID: 0c3f97d3e6d8
Revises: d0d21c10cf28
Create Date: 2021-10-02 17:44:15.240600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3f97d3e6d8'
down_revision = 'd0d21c10cf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotgun_cotisant_entry', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shotgun_cotisant_entry', 'last_name')
    # ### end Alembic commands ###
