"""corrected typos

Revision ID: d0d21c10cf28
Revises: 0ad57c240d77
Create Date: 2021-10-02 17:43:30.430267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d21c10cf28'
down_revision = '0ad57c240d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotgun_cotisant_entry', sa.Column('email', sa.String(), nullable=True))
    op.add_column('shotgun_cotisant_entry', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('shotgun_cotisant_entry', sa.Column('vr_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_shotgun_cotisant_entry_vr_username'), 'shotgun_cotisant_entry', ['vr_username'], unique=True)
    op.create_unique_constraint(None, 'shotgun_cotisant_entry', ['phone_number'])
    op.create_unique_constraint(None, 'shotgun_cotisant_entry', ['email'])
    op.add_column('shotgun_entry', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('shotgun_entry', sa.Column('email', sa.String(), nullable=True))
    op.add_column('shotgun_entry', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_shotgun_entry_email'), 'shotgun_entry', ['email'], unique=True)
    op.create_unique_constraint(None, 'shotgun_entry', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shotgun_entry', type_='unique')
    op.drop_index(op.f('ix_shotgun_entry_email'), table_name='shotgun_entry')
    op.drop_column('shotgun_entry', 'phone_number')
    op.drop_column('shotgun_entry', 'email')
    op.drop_column('shotgun_entry', 'last_name')
    op.drop_constraint(None, 'shotgun_cotisant_entry', type_='unique')
    op.drop_constraint(None, 'shotgun_cotisant_entry', type_='unique')
    op.drop_index(op.f('ix_shotgun_cotisant_entry_vr_username'), table_name='shotgun_cotisant_entry')
    op.drop_column('shotgun_cotisant_entry', 'vr_username')
    op.drop_column('shotgun_cotisant_entry', 'phone_number')
    op.drop_column('shotgun_cotisant_entry', 'email')
    # ### end Alembic commands ###
